version: "3.9"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=busness
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/busness?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/home/node/app/wait-for.sh", "postgres:5432", "--" ]
    command: [ "npm" "start" ]